### ISSUE TITLE
Roadmap to 1.0?

### ISSUE THREAD

**Issue by BradPatras** [kean/CreateAPI#212]
I'm evaluating using this library instead of OpenAPI's swift5 generator or Apple's generator and I have to say I'm really pleased with how it works, great work team! That said I am a little concerned about the slowdown in PR, Issue and Release activity in the past 12-ish months. There seem to be quite a few quality PRs open that look like they could have been closed months (or years) ago that address some pretty important things (the improved handling of `defaults` specifically).

Is there a roadmap towards a 1.0 release or has this library been abandoned?

**Comment by BradPatras** [comment]
After a little more digging I found that CreateAPI is now maintained primarily by @cookpad, which @liamnichols seems to be a member of. @liamnichols Do you have any input on this issue?

**Comment by kean** [comment]
Hey, @liamnichols please let me know if I can help. I personally don't have the resources to contribute to it anymore, but I'd be happy to facilitate adding new contributors.

> OpenAPI's swift5 generator or Apple's generator

Yeah, too much competition, including now Swift-focused.

**Comment by liamnichols** [comment]
Hello 👋 

I'm sorry for the lack of activity on my side here. I have been meaning to followup but it just always seems to drop to the bottom of my priority list. Thanks for the tag though. 

I did take over maintenance from @kean with some backing from my employer at the time however due to changes, I have also struggled to keep on top of things.

The path to 1.0 is a bit of a tricky one and I haven't been able to revisit it since the introduction of Apple's own generator. I think it's important to understand CreateAPIs place in the ecosystem as this is important for deciding where we need to focus.

Personally I had become caught up by some underlying changes that needed to be made to keep CreateAPI viable long term. Part of this involves supporting OpenAPI 3.1 schemas because this requires a large amount of refactoring to decouple schema parsing, customisation and code generation into three distinct components (while maintaining the speed of the current implementation). 

Too much of the current customisation/code generation logic sits tightly coupled to the `OpenAPIKit30` module. This has made me hesitant to accept some PRs focusing on new customisation points before addressing this, but at the same time, getting the foundations in place is a huge task and I haven't had any time to focus on it and unfortunately I don't see that changing anytime soon.

Anyway, back to the original question about 1.0 roadmap... I think the first step will be to identify other contributors who are willing to become maintainers and to help bring us to a 1.0 release. Thanks @kean for offering support here. I'm not quite sure on the best way to do this, so I am open to suggestions 🙏

**Comment by kean** [comment]
Thanks for the expanded answer, Liam, and I appreciate your team helping bring it to the current state. It's not technically 1.0, but it's nicely packaged, available via Homebrew, and offers a lot of value in its current form. In my experience, it's head and shoulders above the alternatives in the aspects that I care about.

Unfortunately, I stopped using it after switching jobs, so I was no longer personally invested in it. With Apple now in the mix, I'm not sure it's worth spending resources on evolving a competing tool, especially since there are other alternatives. But it goes without saying that it's not immediately going anywhere any time soon, and I can't imagine it's stopping working. Supporting new OpenAPI features and versions is another question.

👋  If someone is willing to step up and maintain it or evolve it, please, feel free to reach out to me (here or on Bsky or Mastodon). If no maintainers are found within a couple of months, I'll communicate in the README the status of the tool.

**Comment by BradPatras** [comment]
I really appreciate the responses, it helps a ton to know where the project sits your your guys' minds. 

Even though I believe the CreateAPI generator is cleaner and more user-friendly than the Apple generator I do agree that the existence of the Apple tool makes it harder to justify pouring a bunch of time and effort into maintaining this one.
